### PR TITLE
Add/full calendar

### PR DESCRIPTION
**Pull request by StevenDufresne**
# Description
I connected backend data to the Full Calendar library to see what it would look like. This is an early PR to get us all in line with the approach.

### Questions to answer
1. Are we good with this approach?
2. Should we just run with FullCalendar?

# Screenshot
Calendar With Events

### CODE REVIEW

**Comment by ryelle** [comment]
Bad news: This is _really_ not accessible— as it is, I don't think we can use these views, unless we defaulted the page to an (accessible) list view.

Good news: I'm playing with a custom view (using the plugin system), and it's really convoluted but it might work. I'm focusing on getting a month view functional, and if that works, we should be OK to move forward with FullCalendar.

**Comment by ryelle** [comment]
Also, i just added the *-loaders to package.json, since I was getting build errors without them

**Comment by StevenDufresne** [comment]
@ryelle For educational purposes, where does the calendar fail miserably?

**Comment by ryelle** [comment]
I tested with both keyboard-only navigation, and with VoiceOver. It does _okay_ with keyboard, but I think that's partially to do with it only having simple events. The screen reader is where it fails pretty badly.

- The month-table is not a proper table, instead every row is its own table. It's not possible to navigate up-down between weeks (like from Wed to Wed), which would be expected for this format.
- Every empty cell is read out to me, and the month for some reason has two rows for every week (one empty), so it's very noisy for a screen reader user to get to any relevant data.
- Each date is not a single cell, but instead everything is rows— so you read all the dates out, then all the every first event on a day, then every second event, etc; as opposed to hearing all the events on the same day.

<details>
    <summary>VoiceOver output for the week with the example events</summary>
VoiceOver reads out each item like this as I move through the page (some of this is expected because that's how tables work, like the row/column indications).
<pre>
"Level 2 table 7 columns 1 row"
"row 1 blank, column 1"
"blank, column 2"
"blank, column 3"
"blank, column 4"
"blank, column 5"
"blank, column 6"
"blank, column 7"
"Level 2 table 7 columns 2 rows"
"row 1 16, column 1"
"17, column 2"
"18, column 3"
"19, column 4"
"20, column 5"
"21, column 6"
"22, column 7"
"row 2 16 spans 3 rows blank, column 1"
"17 spans 3 rows blank, column 2"
"18 spans 3 rows blank, column 3"
"19 spans 3 rows blank, column 4"
"20 9:57p A monthly meeting, column 5"
"21 spans 3 rows blank, column 6"
"22 spans 3 rows blank, column 7"
"row 2 20 9:57p A weekly meeting, column 5"
"row 3 20 9:57p Third Wednesday of each month, column 5"
</pre>
</details>

**Pull request closed without merging**
