### PR TITLE
Update cancelled events

### PR DESCRIPTION
**Pull request by ryelle**
Super rough iteration to display cancellation status in the modal & on the list view:

Screen Shot 2020-03-09 at 2 04 41 PM

Screen Shot 2020-03-09 at 2 04 30 PM

### CODE REVIEW

**Comment by tellyworth** [comment]
This looks good so far (and thanks for cleaning up my JS!). What are you thinking for the calendar view?

In the list view, should the whole item be shown differently, like greyed out or with a specially coloured background? I could see people not noticing the text if they're skimming.

**Comment by ryelle** [comment]
I wasn't really sure about how it should look, especially with the style updates in #62. The list… yeah, a light grey background sounds good, maybe with less information (like, remove the location?) so it's easier to visually skip.

The calendar view seems tricky, since some of the colors already have a borderline-accessible contrast ratio. I was thinking maybe a  ❌  icon or some stylized text (strikethrough, maybe? though that's not the most readable/accessible either).

**Comment by StevenDufresne** [comment]
We could make sure of the  [notice component](https://developer.wordpress.org/block-editor/components/notice/).

Screenshot

**Comment by tellyworth** [comment]
I like the strikethrough idea, it seems semantic and hard to miss. Would it be accessible enough if you can still click to see the details in the modal?

**Comment by tellyworth** [comment]
Related to this: how should the shortcode (used in sidebar widgets) display cancelled meetings? Should it strikethrough or otherwise call out the cancelled instance, or is it better to simply display the next non-cancelled date?

Here's what it looks like now:

Screen Shot 2020-03-10 at 2 11 29 pm

**Comment by tellyworth** [comment]
Another question that occurred to me when working on the shortcode: "This meeting has been cancelled" could be read as meaning that all future events have been cancelled. 

Perhaps it should say something like "This event has been cancelled. The next occurrence of this meeting will be on yyyy-mm-dd"?

**Comment by StevenDufresne** [comment]
> I like the strikethrough idea, it seems semantic and hard to miss. Would it be accessible enough if you can still click to see the details in the modal?

I agree, strikethrough would be a good choice.

**Comment by StevenDufresne** [comment]
I didn't block the modal on the event since the user should still be able to see the data. So it's visually disabled but still clickable.

**Current State:**
s
s
s

**Comment by tellyworth** [comment]
This looks great!

**Comment by ryelle** [comment]
I just pushed some changes to keep the contrast at accessible levels — as much as the opacity is a good indicator for cancelled, the text there should still be readable, so it needs to have a contrast ratio of > 4.5 against the background. I think the strikethrough alone is enough of an indicator, right?

**Pull request merged**
