### PR TITLE
Try/event colors

### PR DESCRIPTION
**Pull request by StevenDufresne**
Related to: https://github.com/Automattic/meeting-calendar/issues/32

This PR:
- Add color to teams in both views
- Colors teams are from here (https://make.wordpress.org/meta/handbook/documentation/profile-badges/)

**Screenshots:**

List View

Calendar

### CODE REVIEW

**Comment by tellyworth** [comment]
I like it, I'm having an issue thought where this has turned the calendar text unreadably tiny in the Twenty Twenty theme:
Screen Shot 2020-03-04 at 5 13 09 pm

**Comment by StevenDufresne** [comment]
> I like it, I'm having an issue thought where this has turned the calendar text unreadably tiny in the Twenty Twenty theme:
Ok. I'm learning how challenging it is to work with different themes. That's probably happening because of a crank down of the font size on `html` element. I guess it's why i see so many pixel definitions in css, you can't rely on `rem` or `em` units.

I'll remove the restriction.

**Comment by tellyworth** [comment]
Yep that did the trick!

**Comment by ryelle** [comment]
I tweaked the CSS somewhat to fix some accessibility issues with hover/focus & too-light backgrounds, and also apply to the dropdown menu… but I'm not sure I like it:

Screen Shot 2020-03-04 at 7 07 10 PM

**Pull request merged**
